name: cabinfy

services:
  postgres:
    restart: always
    image: postgres:16.8-alpine3.20
    container_name: cabinfy-postgres
    environment:
      POSTGRES_DB: cabinfy
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cabinfy-backend
    environment:
      NODE_ENV: production
    networks:
      - backend_network
      - frontend_network
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8081:8081"

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cabinfy-frontend
    depends_on:
      - backend
    networks:
      - frontend_network
    ports:
      - "5173:5173"

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
