version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: hotel-backend
    restart: always
    environment:
      - PORT=8080
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - PASS_RESET_BASE_URL=${PASS_RESET_BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: hotel-frontend
    restart: always
    environment:
      - NODE_ENV=production

  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    volumes:
      - /home/nicolas/ssl:/etc/ssl
    container_name: nginx_server
    restart: always
    ports:
      - 80:80
      - 443:443
